# Generated by Django 4.0.4 on 2022-05-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbfname', models.CharField(max_length=50)),
                ('dblname', models.CharField(max_length=50)),
                ('dbemail', models.CharField(max_length=100)),
                ('dbpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
