# Generated by Django 4.0.4 on 2022-05-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(max_length=50)),
                ('dbemail', models.CharField(max_length=100)),
                ('dbsubject', models.CharField(max_length=50)),
                ('dbmessage', models.CharField(max_length=500)),
            ],
        ),
    ]
